reviews/reviews/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rev_system.urls1'))
]

reviews/rev_system/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        app_label = 'rev_system'

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    text = models.TextField()
    rating = models.IntegerField()

reviews/rev_system/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from rev_system.models import Product, Review



def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})

def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'product_detail.html', {'product': product})

def add_review(request, pk):
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        author = request.POST['author']
        text = request.POST['text']
        rating = request.POST['rating']
        review = Review(product=product, author=author, text=text, rating=rating)
        review.save()
        return redirect('product_detail',id=product_id)
    
def index(request):
    return render(request, 'index.html')

reviews/rev_system/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Головна сторінка</title>
</head>
<body>
    <h1>Ласкаво просимо на головну сторінку!</h1>
</body>
</html>

reviews/rev_system/templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.name }}</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
    <p>{{ product.description }}</p>
    <p>Ціна: {{ product.price }}</p>

    <h2>Відгуки:</h2>
    <ul>
        {% for review in product.review_set.all %}
            <li>
                <p>Автор: {{ review.author }}</p>
                <p>Текст відгуку: {{ review.text }}</p>
                <p>Рейтинг: {{ review.rating }}</p>
            </li>
        {% empty %}
            <li>На жаль, на цей продукт поки що немає відгуків.</li>
        {% endfor %}
    </ul>
</body>
</html>

reviews/rev_system/templates/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список продуктів</title>
</head>
<body>
    <h1>Список продуктів</h1>
    <ul>
        {% for product in products %}
            <li>{{ product.name }} - {{ product.price }}</li>
        {% endfor %}
    </ul>
</body>
</html>